export const Routes = {
	home: '/',
	auth: '/auth/login',
	refreshPassword: '/auth/refresh',
	user: '/dashboard/user/',
	userEdit: (id: string) => `/dashboard/user/${id}`,
	userCreate: `/dashboard/user/form`,
	class: '/dashboard/class/',
	classEdit: (id: string) => `/dashboard/class/${id}`,
	classCreate: `/dashboard/class/form`,
	bodyMeasurement: '/dashboard/bodyMeasurement/',
	bodyMeasurementEdit: (id: string) => `/dashboard/bodyMeasurement/${id}`,
	bodyMeasurementCreate: `/dashboard/bodyMeasurement/form`,
	frequencies: '/dashboard/frequencies/',
	frequenciesEdit: (id: string) => `/dashboard/frequencies/${id}`,
	frequenciesCreate: `/dashboard/frequencies/form`,
	subscription: '/dashboard/subscription/',
	subscriptionEdit: (id: string) => `/dashboard/subscription/${id}`,
	subscriptionCreate: `/dashboard/subscription/form`,
	paymentHistory: '/dashboard/paymentHistory/',
	paymentHistoryEdit: (id: string) => `/dashboard/paymentHistory/${id}`,
	paymentHistoryCreate: `/dashboard/paymentHistory/form`,
	dashboard: '/dashboard/dashboard',
	notFound: '/error/404',
	forbidden: '/error/403',
	unauthorized: '/error/401',
	internalServerError: '/error/500',
	patientNotFound: '/error/patient/404',
};
